# Production docker-compose file
version: '3.8'

services:
  app:
    # image: ghcr.io/masa162/uch:latest
    build: .
    container_name: my-app-container
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    depends_on:
      - db
    restart: unless-stopped

  ai-butler:
    build: 
      context: ./scripts/ai-butler
      dockerfile: Dockerfile
    container_name: my-ai-butler-container
    env_file:
      - ./scripts/ai-butler/.env
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - butler-temp:/app/temp

  db:
    image: postgres:16-alpine
    container_name: my-db-container
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./prisma/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    env_file:
      - .env.production

volumes:
  db-data:
  butler-temp: