# docker-composeファイルのバージョンを指定
version: '3.8'

# ここに、起動したいコンテナ（サービス）を定義していく
services:
  # 1つ目のサービス：Next.jsアプリケーション
  app:
    # 現在のディレクトリにあるDockerfileを使ってイメージをビルドする
    build: .
    # コンテナに`my-app-container`という名前を付ける
    container_name: my-app-container
    # ポートフォワーディング：ホストの3000番をコンテナの3000番に繋ぐ
    ports:
      - "3000:3000"
    # .envファイルから環境変数を読み込む
    env_file:
      - .env
    # dbサービスが起動してからappサービスを起動するように依存関係を設定
    depends_on:
      - db

  # 2つ目のサービス：PostgreSQLデータベース
  db:
    # Docker Hubにある公式のpostgresイメージのバージョン16-alpineを使用する
    image: postgres:16-alpine
    # コンテナに`my-db-container`という名前を付ける
    container_name: my-db-container
    # データを永続化するために、db-dataという名前のVolumeをコンテナの/var/lib/postgresql/dataに接続する
    volumes:
      - db-data:/var/lib/postgresql/data
    # .envファイルからDBのパスワードなどを環境変数として読み込む
    env_file:
      - .env
    # コンテナがクラッシュしても自動的に再起動する
    restart: always

# データの永続化に使うVolumeを定義
volumes:
  db-data: