# Production docker-compose file
version: '3.8'

services:
  app:
    # image: ghcr.io/masa162/uch:latest
    build: .
    container_name: my-app-container
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    container_name: my-db-container
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env.production
    environment:
      - POSTGRES_USER=uch_user
      - POSTGRES_PASSWORD=uch_password
      - POSTGRES_DB=uch_dev

volumes:
  db-data: